export const SmallItems = [
  {
    rank: '1',
    companyLogo: 'https://assets.entrepreneur.com/static/tcc/logos/TCC_Scribe_Media_LLC_Logo_300x300.png?width=80',
    title: 'Scribe Media',
    location: "Austin, Texas",
    sector: 'Publishing',
    companyBio: 'Scribe helps professionals share their knowledge by turning their ideas into professionally published books and speeches. Its clients include Fortune 500 CEOs and executives, doctors, lawyers, financial advisors, high level consultants and entrepreneurs.',
    companyImg: 'https://assets.entrepreneur.com/static/tcc/profile/TCC_ScribeMedia_1920x1080.png?width=550',
    yearFounded: '2014',
    numEmployee: '35',
    url: 'https://scribemedia.com/',
    cName: 'nav-links',
  },
  {
    rank: '2',
    companyLogo: 'https://assets.entrepreneur.com/static/tcc/logos/TCC_Scribe_Media_LLC_Logo_300x300.png?width=80',
    title: 'Scribe Media',
    location: "Austin, Texas",
    sector: 'Publishing',
    companyBio: 'Scribe helps professionals share their knowledge by turning their ideas into professionally published books and speeches. Its clients include Fortune 500 CEOs and executives, doctors, lawyers, financial advisors, high level consultants and entrepreneurs.',
    companyImg: 'https://assets.entrepreneur.com/static/tcc/profile/TCC_ScribeMedia_1920x1080.png?width=550',
    yearFounded: '2014',
    numEmployee: '35',
    url: 'https://scribemedia.com/',
    cName: 'nav-links',
  },
  {
    rank: '3',
    companyLogo: 'https://assets.entrepreneur.com/static/tcc/logos/TCC_Scribe_Media_LLC_Logo_300x300.png?width=80',
    title: 'Scribe Media',
    location: "Austin, Texas",
    sector: 'Publishing',
    companyBio: 'Scribe helps professionals share their knowledge by turning their ideas into professionally published books and speeches. Its clients include Fortune 500 CEOs and executives, doctors, lawyers, financial advisors, high level consultants and entrepreneurs.',
    companyImg: 'https://assets.entrepreneur.com/static/tcc/profile/TCC_ScribeMedia_1920x1080.png?width=550',
    yearFounded: '2014',
    numEmployee: '35',
    url: 'https://scribemedia.com/',
    cName: 'nav-links',
  },
  {
    rank: '4',
    companyLogo: 'https://assets.entrepreneur.com/static/tcc/logos/TCC_Scribe_Media_LLC_Logo_300x300.png?width=80',
    title: 'Scribe Media',
    location: "Austin, Texas",
    sector: 'Publishing',
    companyBio: 'Scribe helps professionals share their knowledge by turning their ideas into professionally published books and speeches. Its clients include Fortune 500 CEOs and executives, doctors, lawyers, financial advisors, high level consultants and entrepreneurs.',
    companyImg: 'https://assets.entrepreneur.com/static/tcc/profile/TCC_ScribeMedia_1920x1080.png?width=550',
    yearFounded: '2014',
    numEmployee: '35',
    url: 'https://scribemedia.com/',
    cName: 'nav-links',
  },
  {
    rank: '5',
    companyLogo: 'https://assets.entrepreneur.com/static/tcc/logos/TCC_Scribe_Media_LLC_Logo_300x300.png?width=80',
    title: 'Scribe Media',
    location: "Austin, Texas",
    sector: 'Publishing',
    companyBio: 'Scribe helps professionals share their knowledge by turning their ideas into professionally published books and speeches. Its clients include Fortune 500 CEOs and executives, doctors, lawyers, financial advisors, high level consultants and entrepreneurs.',
    companyImg: 'https://assets.entrepreneur.com/static/tcc/profile/TCC_ScribeMedia_1920x1080.png?width=550',
    yearFounded: '2014',
    numEmployee: '35',
    url: 'https://scribemedia.com/',
    cName: 'nav-links',
  },
]