export const LargeItems = [
  {
    rank: '1',
    title: 'Goosehead Insurance',
    location: "Westlake, Texas",
    sector: 'General Insurance',
    companyBio: 'Goosehead Insurance is an independent personal lines insurance agency. Goosehead represents more than 80 insurance companies that underwrite personal lines and small commercial lines risks, and its operations include a network of seven corporate sales offices and more than 400 franchise locations.',
    yearFounded: '2013',
    numEmployee: '341',
    url: 'https://www.gooseheadinsurance.com/',
  },
  {
    rank: '2',
    title: 'Berkshire Hathaway HomeServices Ambassador Real Estate',
    location: "Omaha, Neb.",
    sector: 'Agents and Brokers',
    companyBio: 'Berkshire Hathaway HomeServices Ambassador Real Estate offers real estate services that include relocation, fine homes, rentals, short sales, commercial and investment properties.',
    yearFounded: '1984',
    numEmployee: '661',
    url: 'https://www.bhhsamb.com/',
  },
  {
    rank: '3',
    title: 'HubSpot',
    location: "Cambridge, Mass.",
    sector: 'B2B Software',
    companyBio: 'HubSpot is an inbound marketing, sales and CRM growth stack. HubSpot Marketing includes social media publishing and monitoring, blogging, SEO, website content management, email marketing, marketing automation and reporting and analytics. HubSpot Sales enables sales and service teams to have more effective conversations with leads, prospects and customers. HubSpot CRM helps sales teams organize, track and grow their pipeline.',
    yearFounded: '2006',
    numEmployee: '1633',
    url: 'https://www.hubspot.com/',
  },
  {
    rank: '4',
    title: 'Power Home Remodeling Group',
    location: "Chester, Pa",
    sector: 'Home Improvement and Remodeling',
    companyBio: 'Power Home Remodeling Group is an exterior home remodeler. It provides energy-saving and environmentally friendly remodeling solutions to residents across its operating territories.',
    yearFounded: '1992',
    numEmployee: '2284',
    url: 'http://www.powerhrg.com',
  },
  {
    rank: '5',
    title: 'Curriculum Associates',
    location: "North Billerica, Mass",
    sector: 'Publishing',
    companyBio: "Curriculum Associates focuses on a blended learning approach, evolving along with schools as they focus more on digital content. It designs print and online instructional materials, screens and assessments, along with data management tools to address the needs of today's student and help teachers save time in the classroom.",
    yearFounded: '1969',
    numEmployee: '808',
    url: 'https://www.curriculumassociates.com/',
  }
]