export const MediumItems = [
  {
    rank: '1',
    title: 'Zurixx',
    location: "Cottonwood Heights, Utah",
    sector: 'Financial Education',
    companyBio: 'Zurixx develops, promotes, sells and fulfills financial education programs throughout the United States and Canada. Its multi-phase educational process equips students with the tools, knowledge and resources they need to be financially successful. Zurixx partners with internationally-known celebrities from ABC, A&E, HGTV, and DIY Networks.',
    yearFounded: '2012',
    numEmployee: '81',
    url: 'http://www.zurixx.com',
  },
  {
    rank: '2',
    title: 'Upside Travel',
    location: "Washington, DC",
    sector: 'Travel / Vacation',
    companyBio: 'Upside is an online travel service exclusively for business travelers.',
    yearFounded: '2015',
    numEmployee: '87',
    url: 'http://www.upside.com',
  },
  {
    rank: '3',
    title: '8z Real Estate',
    location: "Boulder, Colo.",
    sector: 'Agents / Brokers',
    companyBio: '8z Real Estate is a real-estate brokerage firm that provides home buyers and sellers with market data and online tools, along with the knowledge and expertise of professionals on the ground.',
    yearFounded: '2009',
    numEmployee: '159',
    url: 'https://8z.com',
  },
  {
    rank: '4',
    title: 'CBH Homes',
    location: "Meridian, Idaho",
    sector: 'New Home Construction',
    companyBio: 'CBH Homes is a home builder and real-estate firm.',
    yearFounded: '1992',
    numEmployee: '89',
    url: 'https://cbhhomes.com/',
  },
  {
    rank: '5',
    title: 'N2 Publishing',
    location: "Wilmington, N.C.",
    sector: 'Neighborhood Publications',
    companyBio: 'N2 Publishing produces neighborhood publications that create a sense of community and support local businesses.',
    yearFounded: '2004',
    numEmployee: '230',
    url: 'https://n2pub.com/',
  },
]